bot_start
bassdarkside/Anvi-Bot-A pull request #2
Opened 2023-09-12 20:59 UTC by Olha-Zhernosek

додала гілку bot_start, там тільки мінімум для відпрацьовування кнопки start

2023-09-14 10:50 UTC, bassdarkside requested changes

2023-09-14 10:50 UTC, bassdarkside commented on bot_start/requirements.txt
Порожній файл

2023-09-14 11:58 UTC, Olha-Zhernosek commented on bot_start/token_anvi.txt
> +6691900046:AAGLfl7y1lE9XuI_0JSMUrK3St1HWVRIBfo
зробила rm, файл був у гіт_ігнорі, але, мабудь робила не за потрібною послідовністю, тому потрапив у репозиторій, виправлено

2023-09-14 11:59 UTC, Olha-Zhernosek commented on bot_start/requirements.txt
так, бо мені для парсингу ще сюди додавати, він був зроблений заздалегідь

2023-09-14 12:04 UTC, Olha-Zhernosek commented on bot_start/token_anvi.txt
> +6691900046:AAGLfl7y1lE9XuI_0JSMUrK3St1HWVRIBfo
але тепер токен зробив пін тут у коментарях)))

2023-09-14 18:51 UTC, ValentynaRudenko commented
@Olha-Zhernosek @bassdarkside  - ви круті! в мене коментарів не має :)

2023-09-16 12:05 UTC, bassdarkside approved these changes

2023-09-16 12:53 UTC, merged