Catalog
bassdarkside/Anvi-Bot-A pull request #4
Opened 2023-09-17 20:38 UTC by ValentynaRudenko

@Olha-Zhernosek @bassdarkside @bielanm
Привіт!

Додала окремим файлом каталог та функції створення кнопок.

Додала їх як модулі у файл `bot_initial`

2023-09-19 14:30 UTC, bassdarkside requested changes

2023-09-19 14:30 UTC, bassdarkside commented on bot_start/bot_initial.py
> +catalog.start()
не працює.
У такому випадку наш бот не працюватиме

2023-09-19 14:33 UTC, bassdarkside requested changes
Наш бот не запуститься. Потрібні зміни (

2023-09-21 06:53 UTC, ValentynaRudenko commented on bot_start/bot_initial.py
> +catalog.start()
Перероблюю, щоб було все в одному файлі - так працює.
Оновлю вже з доробкою каталога

2023-09-21 17:13 UTC, bassdarkside approved these changes
🤩

2023-09-23 11:16 UTC, bielanm commented on bot_start/bot_initial.py
> +# # Handler for all messages
А чому закоментовано цей хендлєр?

2023-09-23 14:29 UTC, ValentynaRudenko commented on bot_start/bot_initial.py
> +# # Handler for all messages
Цей хендлер писала Оля, коли створювала бота.

Замість нього зараз створений хендлер, що запускає клавіатуру.

Я правильно орзумію, що треба просто прибрати зайвий код?

2023-09-24 09:14 UTC, merged